app/models.py
from datetime import datetime
from app import db


class Alert_Jack(db.Model):
    __tablename__="alert_jack"
    __table_args__ = {"useexisting": True}
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    alert_id = db.Column(db.String(100))
    yesornot = db.Column(db.Integer)
    deploy_id = db.Column(db.String(100))
    source_id = db.Column(db.String(100))
    addtime = db.Column(db.DateTime, index=True, default=datetime.now)


if __name__ == "__main__":
    # db.metadata.clear()

    db.create_all()

app/Dface/__init__.py
from flask import Blueprint
dface = Blueprint("Dface", __name__)

import app.Dface.views

app/Dface/views.py
from app import app
from app import db
from app.Dface import dface
from app.models import Alert_Jack
from flask import render_template, redirect, url_for, flash, request, session, Response, jsonify
import json
import pymysql


def executesql(sql1):
    db = pymysql.connect(host='172.16.1.6', user='root',
                         password='Tunicorn@hf#2017', db='dface_community', port=3306, charset='utf8mb4')
    cur = db.cursor()
    sql_select = sql1
    qret = cur.execute(sql_select)
    rows = cur.fetchall()
    db.commit()
    cur.close()
    db.close()
    return rows


@dface.route("/")
def index():
    if request.method == 'GET':
        return render_template("dface/admin_list.html")


# @dface.route("/verity_list/<string:deployid>/<string:sourceid>", methods=["GET", "POST"])
@dface.route("/verity_list/", methods=["GET", "POST"])
def verity_list():
    if request.method == "GET":
        return render_template("dface/verity_list.html")
    if request.method == "POST":
        # data = json.loads(request.form.get("data"))
        data = request.form
        # deployid = request.form["deployid"]
        # data = json.loads(str(request.data))
        deployid = data["deployid"]
        sourceid = data["sourceid"]
        # alerts = executesql("")
        sql = "select id, capture_id, capture_file_path,asset_path,face_id, score  from alert where deploy_id="+deployid+" and source_id="+sourceid
        alert_datas = executesql(sql)
        # alert_datas = list(alert_datas)
        # print(alert_datas)
        str = "/mnt/storage4/dface/6w_zhuzhou/430202193108083647.jpg"

        sql_2 = "select count(1)  from alert where deploy_id=" + deployid + " and source_id=" + sourceid
        sql_count = executesql(sql_2)
        return render_template("dface/verity_list.html", datas=alert_datas, sql_count=sql_count)




@dface.route("/verity_look/<string:alertid>", methods=["GET"])
def verity_look(alertid=None):
    if request.method == "GET":
        alertjacksql = "select alert_id, yesornot from alert_jack"
        alertjacks = executesql(alertjacksql)
        alertjacksql_self = "select alert_id, yesornot from alert_jack where alert_id='"+alertid+"'"
        alertjack = executesql(alertjacksql_self)
        sql = "select id, capture_file_path,asset_path,score, deploy_id, source_id from alert where id='"+alertid+"'"
        alertmes = executesql(sql)
        suc_count_sql = "select count(1)  from alert_jack where yesornot=1"
        err_count_sql = "select count(1)  from alert_jack where yesornot=0"
        suc_count = executesql(suc_count_sql)
        err_count = executesql(err_count_sql)
        return render_template(
            "dface/verity_look.html",
            alertjack=alertjack,
            alertjacks=alertjacks,
            alert=alertmes,
            alertid=alertid,
            suc_count=suc_count,
            err_count=err_count
        )


@dface.route("/verity_ajax/", methods=["POST"])
def verity_ajax():
    if request.method == "POST":
        # data = json.loads(request.data)
        data = request.form
        sourceid = data["sourceid"]
        deployid = data["deployid"]
        alertidold = data["alertid"]
        yesornot = data["yesornot"]
        # 保存数据
        alerts_count = Alert_Jack.query.filter_by(alert_id=alertidold).count()
        if alerts_count == 0:
            alert_jack = Alert_Jack(
                deploy_id=deployid,
                alert_id=alertidold,
                source_id=sourceid,
                yesornot=yesornot
            )
            db.session.add(alert_jack)
            db.session.commit()
        # 进入下一页
        sql = "select id, capture_file_path,asset_path,score, deploy_id, source_id  from alert where id='" + alertidold + "'"
        sqls="select id, capture_id, capture_file_path,asset_path,face_id, score  from alert where deploy_id="+deployid+" and source_id="+sourceid
        suc_count_sql = "select count(1)  from alert_jack where yesornot=1"
        err_count_sql = "select count(1)  from alert_jack where yesornot=0"
        datas = executesql(sqls)
        for i in range(0, len(datas)):
            if datas[i][0] == alertidold and i < len(datas)-1:
                # print(datas[i][0])
                alertidnew = datas[i+1][0]
                break

            if i == len(datas)-1:
                suc_count = executesql(suc_count_sql)
                err_count = executesql(err_count_sql)
                returndata = {
                    "status": 'success',
                    "alertnext": datas[i][0],
                    "msg": "匹配结束，当前为最后一条记录",
                    "suc_count":suc_count,
                    "err_count":err_count
                    }
                return Response(json.dumps(returndata), content_type='application/json')

        returndata = { "status": 'success', "alertnext": alertidnew, "msg": "下一个" }

        return Response(json.dumps(returndata), content_type='application/json')

app/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
import pymysql
import os


app = Flask(__name__)
app.debug = True
app.config["SQLALCHEMY_DATABASE_URI"] = "mysql+pymysql://root:Tunicorn@hf#2017@172.16.1.6:3306/dface_community"
app.config["SQLALCHEMY_TRACK_MODIFICATIONS"] = True
# app.config['SECRET_KEY'] = '1f31472e4e774f00865b6ca0c5cc08d8'
# app.config['UP_DIR'] = os.path.join(os.path.abspath(os.path.dirname(__file__)), "static/uploads/")

db = SQLAlchemy(app)
from app import blueview
from app import filter_utils

app/templates/dface/admin.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>微电影管理系统</title>
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <link rel="shortcut icon" href="{{ url_for('static', filename='base/images/logo.png')}}">
    <link rel="stylesheet" href="{{ url_for('static', filename='admin/bootstrap/css/bootstrap.min.css')}}">
    <link rel="stylesheet" href="{{ url_for('static', filename='fonts/css/font-awesome.min.css')}}">
    <link rel="stylesheet" href="{{ url_for('static', filename='ionicons/css/ionicons.min.css')}}">
    <link rel="stylesheet" href="{{ url_for('static', filename='admin/dist/css/AdminLTE.min.css')}}">
    <link rel="stylesheet" href="{{ url_for('static', filename='admin/dist/css/skins/_all-skins.min.css')}}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='admin/plugins/datepicker/datepicker3.css')}}">
    <style>
        *{
            font-family:"Microsoft YaHei";
        }
        .table>tbody>tr>td, .table>tbody>tr>th, .table>tfoot>tr>td, .table>tfoot>tr>th, .table>thead>tr>td, .table>thead>tr>th{
            vertical-align:middle;
            text-align:center;
        }
    </style>
    {% block css %} {% endblock %}
</head>



<body class="hold-transition skin-blue sidebar-mini">
<div class="wrapper">
    <header class="main-header">
        <a href="{{ url_for('Dface.index') }}" class="logo">
            <span class="logo-mini"><img src="{{ url_for('static', filename='base/images/logo.png')}}" style="height:40px;width:40px;">电影系统</span>
            <span class="logo-lg"><img src="{{ url_for('static', filename='base/images/logo.png')}}" style="height:40px;width:40px;">微电影管理系统</span>
        </a>
        <nav class="navbar navbar-static-top">
            <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
                <span class="sr-only">下拉菜单</span>
            </a>
            <div class="navbar-custom-menu">
                <ul class="nav navbar-nav">
                    <li class="dropdown user user-menu">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <img src="{{ url_for('static', filename='admin/dist/img/user2-160x160.jpg')}}"
                                 class="user-image" alt="User Image">
                            <span class="hidden-xs">xxx</span>
                        </a>
                        <ul class="dropdown-menu">
                            <li class="user-header">
                                <img src="{{ url_for('static', filename='admin/dist/img/user2-160x160.jpg')}}"
                                     class="img-circle" alt="User Image">
                                <p>
                                    xxx
                                    <small>2017-06-01</small>
                                </p>
                            </li>
                            <li class="user-footer">
                                <div class="pull-left">
                                    <a href="" class="btn btn-default btn-flat">修改密码</a>
                                </div>
                                <div class="pull-right">
                                    <a href="" class="btn btn-default btn-flat">退出系统</a>
                                </div>
                            </li>
                        </ul>
                    </li>
                </ul>
            </div>
        </nav>
    </header>
    <aside class="main-sidebar">
        <section class="sidebar">
            <div class="user-panel">
                <div class="pull-left image">
                    <img src="{{ url_for('static', filename='admin/dist/img/user2-160x160.jpg')}}" class="img-circle"
                         alt="User Image">
                </div>
                <div class="pull-left info">
                    <p>用户xxx</p>
                    <a href="#"><i class="fa fa-circle text-success"></i> 在线</a>
                </div>
            </div>
            <form action="#" method="get" class="sidebar-form">
                <div class="input-group">
                    <input type="text" name="q" class="form-control" placeholder="搜索...">
                    <span class="input-group-btn">
                        <button type="submit" name="search" id="search-btn" class="btn btn-flat"><i
                                class="fa fa-search"></i>
                        </button>
                    </span>
                </div>
            </form>
            {% include 'dface/grid.html' %}
        </section>
    </aside>
    <div class="content-wrapper">
    <!--内容-->
        {% block content %} {% endblock %}
    <!--内容-->
    </div>
    <footer class="main-footer">
        <div class="pull-right hidden-xs">
            <b>版本</b> 1.0
        </div>
        <strong>版权 &copy; 2017-2018 归<a href="">xxx</a>.</strong> 所有
    </footer>
    <div class="control-sidebar-bg"></div>
</div>

<script src="{{ url_for('static', filename='admin/plugins/jQuery/jQuery-2.2.0.min.js')}}"></script>
<script src="{{ url_for('static', filename='admin/bootstrap/js/bootstrap.min.js')}}"></script>
<script src="{{ url_for('static', filename='admin/plugins/slimScroll/jquery.slimscroll.min.js')}}"></script>
<script src="{{ url_for('static', filename='admin/plugins/fastclick/fastclick.js')}}"></script>
<script src="{{ url_for('static', filename='admin/dist/js/app.min.js')}}"></script>
<script src="{{ url_for('static', filename='admin/dist/js/demo.js')}}"></script>
{#<script src="//cdn.bootcss.com/holder/2.9.4/holder.min.js'"></script>#}
<script src="{{ url_for('static', filename='admin/plugins/datepicker/bootstrap-datepicker.js')}}"></script>
<script src="{{ url_for('static', filename='admin/plugins/datepicker/locales/bootstrap-datepicker.zh-CN.js')}}" charset="UTF-8"></script>
{% block js %} {% endblock %}

</body>
</html>

app/templates/dface/admin_list.html
{% extends 'dface/admin.html' %}

{% block content %}
    <section class="content-header">
        <h1>微电影管理系统</h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> 管理员管理</a></li>
            <li class="active">管理员列表</li>
        </ol>
    </section>
    <section class="content" id="showcontent">
        <div class="row">
            <div class="col-md-12">
                <div class="box box-primary">
                    <div class="box-header">
                        <h3 class="box-title">管理员列表</h3>
                        <div class="box-tools">

                        </div>
                    </div>
                    <div class="box-body table-responsive no-padding">
                        <form method="post" action="{{ url_for("Dface.verity_list") }}">
                            <input type="text" name="deployid" class="form-control pull-right"
                                   placeholder="请输入任务id">
                            <input type="text" name="sourceid" class="form-control pull-right"
                                   placeholder="请输入视频源id">
                            <button id="btn" name="btn" >进入确认</button>
                        </form>

                    </div>
                    <div class="box-footer clearfix">
                        {#                        <ul class="pagination pagination-sm no-margin pull-right">#}
                        {#                            <li><a href="#">首页</a></li>#}
                        {#                            <li><a href="#">上一页</a></li>#}
                        {#                            <li><a href="#">1</a></li>#}
                        {#                            <li><a href="#">2</a></li>#}
                        {#                            <li><a href="#">3</a></li>#}
                        {#                            <li><a href="#">下一页</a></li>#}
                        {#                            <li><a href="#">尾页</a></li>#}
                        {#                        </ul>#}
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}


{% block js %}

    {#    <script>#}
    {#        $(document).ready(function () {#}
    {#            $('#g-1').addClass("active");#}
    {#            $('#g-1-1').addClass("active")#}
    {#        })#}
    {#    </script>#}
{#    <script type="application/javascript">#}
{#        $(document).ready(function () {#}
{#            $("#btn").click(function () {#}
{#                var deployid = $('#deployid').val();#}
{#                var id = $('#id').val();#}
{#                var sourceid = $('#sourceid').val();#}
{#                var data = { "deployid": deployid, "sourceid": sourceid };#}
{#                $.ajax({#}
{#                    type: 'POST',#}
{#                    url: '{{ url_for("Dface.verity_list") }}',#}
{#                    data: JSON.stringify({'a':1,'b':2}),#}
{#                    contentType: 'application/json',#}
{#                    success: function(res) {#}
{#                        alert("成功");#}
{#                    },#}
{#                    error: function (res) {#}
{#                        alert("失败")#}
{#                    }#}
{##}
{#                })#}
{#            })#}
{#        })#}
{#    </script>#}

{% endblock %}

app/templates/dface/grid.html
<ul class="sidebar-menu">
    <li class="header">管理菜单</li>
    <li class="treeview" id="g-1">
        <a href="#">
            <i class="fa fa-home" aria-hidden="true"></i>
            <span>首页</span>
            <span class="label label-primary pull-right">1</span>
        </a>
        <ul class="treeview-menu">
            <li id="g-1-1">
                <a href="{{ url_for('Dface.index') }}">
                    <i class="fa fa-circle-o">告警记录</i>
                </a>
            </li>
            <li id="g-1-2">
                <a href="{{ url_for('Dface.index') }}">
                    <i class="fa fa-circle-o">待更新</i>
                </a>
            </li>
        </ul>
    </li>
</ul>

app/templates/dface/verity_list.html
{% extends 'dface/admin.html' %}

{% block content %}
    <section class="content-header">
        <h1>微电影管理系统</h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> 管理员管理</a></li>
            <li class="active">管理员列表</li>
        </ol>
    </section>
    <section class="content" id="showcontent">
        <div class="row">
            <div class="col-md-12">
                <div class="box box-primary">
                    <div class="box-header">
                        <h3 class="box-title">管理员列表</h3>
                        <div class="box-tools">
                            <div class="input-group input-group-sm" style="width: 150px;">
{#                                <input type="text" name="table_search" class="form-control pull-right"#}
{#                                       placeholder="请输入关键字...">#}

                                <div class="input-group-btn">
                                    <button id="button1" type="submit" class="btn btn-default"><i class="fa fa-search"></i>
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="box-body table-responsive no-padding">
                        {#                        <input type="text" name="deployid" class="form-control pull-right"#}
                        {#                               placeholder="请输入任务id">#}
                        {#                        <input type="text" name="sourceid" class="form-control pull-right"#}
                        {#                               placeholder="请输入视频源id">#}
                        {#                        <button type="submit" class="btn btn-default">进入确认</button>#}
                        <div><span>总计：</span> <span style="color: red">{{ sql_count[0][0] }}</span></div>
                        <table class="table table-hover">
                            <tbody>
                            <tr>

                                <th>alertid</th>
{#                                <th>captureid</th>#}
                                <th>captureurl</th>
                                <th>faceurl</th>
                                <th>faceid</th>
                                <th>score</th>
                                <th>操作</th>

                            </tr>
                            {% for v in datas %}
                                <tr>
                                    <td>{{ v[0] }}</td>
{#                                    <td>{{ v[1] }}</td>#}
                                    <td>
                                        {#                                        <img name="img1" src="http://172.16.1.6/pic/detected/1/2018-11-28/7ec9e11d-17b1-4261-ad29-a958bb287790-1928-0-extend.png"#}
                                        {#                                             style="width: 80px" class="img-responsive center-block" alt="">#}
                                        <img id="img1" src="{{ v[2]|qiepian(19)|pingjie("http://172.16.1.6/pic") }}"
                                             style="width: 140px" class="img-responsive center-block" alt="">
                                    </td>

                                    <td><img id="img2" src="{{ v[3]|qiepian(19)|pingjie("http://172.16.1.6/pic") }}"
                                             style="width: 140px" class="img-responsive center-block" alt="">
                                    </td>
                                    <td>{{ v[4] }}</td>
                                    <td>{{ v[5] }}</td>

                                    <td><a href="{{ url_for("Dface.verity_look", alertid=v[0]) }}">操作</a></td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                    <div class="box-footer clearfix">
                        <ul class="pagination pagination-sm no-margin pull-right">
                            <li><a href="#">首页</a></li>
                            <li><a href="#">上一页</a></li>
                            <li><a href="#">1</a></li>
                            <li><a href="#">2</a></li>
                            <li><a href="#">3</a></li>
                            <li><a href="#">下一页</a></li>
                            <li><a href="#">尾页</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}


{% block js %}

    <script>
        $(document).ready(function () {
            $('#g-1').addClass("active");
            $('#g-1-1').addClass("active");

        })
    </script>
{#    <script>#}
{#    $("#button1").click(function(){#}
{##}
{#        var captureimg = $("#img1").attr("src");#}
{#        var substr = captureimg.slice(19);#}
{#        var captureimgNew = "http://172.16.1.6/pic" + substr;#}
{#        $("#img1").attr("src", captureimgNew);#}
{#        var faceurl = $("#img2").attr("src");#}
{#        var substr2 = faceurl.slice(19);#}
{#        var faceurlNew = "http://172.16.1.6/pic" + substr2;#}
{#        $("#img2").attr("src", faceurlNew);#}
{#    })#}
{#    #}
{#    </script>#}

{% endblock %}

app/templates/dface/verity_look.html
{% extends 'dface/admin.html' %}

{% block content %}
    <section class="content-header">
        <h1>微电影管理系统</h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> 管理员管理</a></li>
            <li class="active">管理员列表</li>
        </ol>
    </section>
    <section class="content" id="showcontent">
        <div class="row">
            <div class="col-md-12">
                <div class="box box-primary">
                    <div class="box-header">
                        <h3 class="box-title">管理员列表</h3>
                        <div class="box-tools">
                            成功个数：<input id="suc" value="{{ suc_count[0][0] }}">
                            错误个数：<input id="err" value="{{ err_count[0][0] }}">
{#                            <button id="ti">统计结果</button>#}
                        </div>

                    </div>
                    <div class="box-body table-responsive no-padding">
                        <div id="p0" data-value="{{ alertid }}">
                            <span id="alertid">id: {{ alertid }}</span>

                            {#                            <input id="deployid" type="" value="{{}}">#}
                            {#                            <input id="alertid" type="" value="">#}
                            {#                            <input id="sourceid" type="" value="">#}
                        </div>
                        <table class="table table-hover">
                            <tbody>
                            <tr>
                                <th>Capture</th>
                                <th>Face</th>
                            </tr>
                            <tr>

                                <td><img id="img1" src="{{ alert[0][1]|qiepian(19)|pingjie("http://172.16.1.6/pic") }}"
                                         class="img-responsive center-block" alt=""></td>
                                <td><img id="img1" src="{{ alert[0][2]|qiepian(19)|pingjie("http://172.16.1.6/pic") }}"
                                         style="width: 200px" class="img-responsive center-block" alt=""></td>
                            </tr>
                            </tbody>
                        </table>
                    </div>
                    <div class="box-footer clearfix" style="text-align: center">
                        <div class="input-group input-group-sm">

                            <div id="p1" class="input-group-btn" data-value="{{ alert[0][4] }}">
                                <button type="submit" id="pipei" name="pipei" class="btn btn-default" value="1"><i
                                        class="fa fa-search" data-value="yes">匹配</i>
                                </button>
                            </div>
                            <div id="p2" class="input-group-btn" data-value="{{ alert[0][5] }}">
                                <button type="submit" id="bupipei" name="bupipei" class="btn btn-default" value="0"><i
                                        class="fa fa-search" data-value="yes">不匹配</i>
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}


{% block js %}

    <script>
        $(document).ready(function () {
            $('#tj').click(function () {
                var suc = $('#suc').attr('value', data.suc_count);
                var err = $('#err').attr('value', data.err_count);
            });
            $("#pipei").click(function () {

                var alertid = $('#p0').attr('data-value');
                var sourceid = $('#p2').attr('data-value');
                var deployid = $('#p1').attr('data-value');
                var data = {
                    "alertid": alertid,
                    'sourceid': sourceid,
                    'deployid': deployid,
                    "yesornot": 1
                };
                $.ajax({
                    type: 'POST',
                    url: '{{ url_for("Dface.verity_ajax") }}',
                    data: data,
                    dataType: 'json',
                    success: function (data) {
                        if (data.status == "success") {


                            window.location.href = "\\verity_look\\" + data.alertnext;
                            alert(data.msg);
                        }
                    },
                    error: function (data) {
                        alert("匹配结束")

                    }
                })
            });
            $("#bupipei").click(function () {
                var alertid = $('#p0').attr('data-value');
                var sourceid = $('#p2').attr('data-value');
                var deployid = $('#p1').attr('data-value');
                var data = {
                    "alertid": alertid,
                    'sourceid': sourceid,
                    'deployid': deployid,
                    "yesornot": 0
                };
                $.ajax({
                    type: 'POST',
                    url: '{{ url_for("Dface.verity_ajax") }}',
                    data: data,
                    dataType: 'json',
                    success: function (data) {
                        if (data.status == "success") {

                            var suc = $('#suc').attr('value', data.suc_count);
                            var err = $('#err').attr('value', data.err_count);
                            window.location.href = "\\verity_look\\" + data.alertnext;
                            alert(data.msg);
                        }
                    },
                    error: function (data) {
                        alert("失败了")
                    }
                })
            });
        })
    </script>



{% endblock %}

app/templates/ui/admin_page.html
{#
    pagination: 页码
    endpoint：Url，对应跳转链接
#}

{% macro render_pagination(pagination, url) %}
    {% if pagination %}
        <ul class="pagination pagination-sm no-margin pull-right">

            <li><a href="{{ url_for(url, page=1) }}">首页</a></li>
            {% if pagination.has_prev %}
                <li><a href="{{ url_for(url, page=pagination.prev_num) }}">上一页</a></li>
            {% else %}
                <li class="disabled"><a href="#">上一页</a></li>
            {% endif %}
            {#    页码循环#}
            {% for v in pagination.iter_pages() %}
                {# 主要是判断鼠标单击页面是否为当前页面，如果是active即可#}
                {% if v == pagination.page %}
                    <li class="active"><a href="#">{{ v }}</a></li>
                {% else %}
                    <li><a href="{{ url_for(url,page=v) }}">{{ v }}</a></li>
                {% endif %}
            {% endfor %}

            {% if pagination.has_next %}
                <li><a href="{{ url_for(url, page=pagination.next_num) }}">下一页</a></li>
            {% else %}
                <li><a class="disabled" href="#">下一页</a></li>
            {% endif %}
            <li><a href="{{ url_for(url, page=pagination.pages) }}">尾页</a></li>
        </ul>
    {% endif %}
{% endmacro %}